services:
  db:
    image: postgres:15
    container_name: lodging_db
    environment:
      POSTGRES_DB: accommodation_management
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: lodging-house-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

volumes:
  postgres_data:
